name: Build and Deploy

on:
  pull_request:
    branches: [main]
    types:
      - closed

jobs:
  Build-and-Push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/vzauartcc/api:${{ github.sha }}
            ghcr.io/vzauartcc/api:master
            ghcr.io/vzauartcc/api:latest
  Deploy-to-Staging:
    needs: Build-and-Push
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s
      - name: Deploy image to cluster
        run: kubectl set image deployment/api-dev api-dev=ghcr.io/vzauartcc/api:${{ github.sha }} --record -n zau-staging-web-stack
      - name: Verify deployment
        run: kubectl rollout status deployment/api-dev -n zau-staging-web-stack
  Deploy-to-Prod:
    needs: Deploy-to-Staging
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s
      - name: Deploy image to cluster
        run: kubectl set image deployment/api api=ghcr.io/vzauartcc/api:${{ github.sha }} --record -n zau-web-stack
      - name: Verify deployment
        run: kubectl rollout status deployment/api -n zau-web-stack
