# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'CI Check' action.

name: CI Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  Verify-App-Builds:
    runs-on: ubuntu-latest

    if: github.event.pull_request.base.ref != 'main'

    steps:
      - name: Checkout master
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Typescript
        run: npx tsc --noEmit
