import { config } from 'dotenv';
import m from 'mongoose';

const configSchema = new m.Schema(
	{
		id: String,
		arConfig1: String,
		arConfig2: String,
		arConfig3: String,
		arConfig4: String,
		drConfig1: String,
		drConfig2: String,
		drConfig3: String,
		drConfig4: String,
		drConfig5: String,
		ssatConfig1: String,
		ssatConfig2: String,
		ssatConfig3: String,
		ssatConfig4: String,
		lcConfig1: String,
		lcConfig2: String,
		lcConfig3: String,
		lcConfig4: String,
		mdwLcConfig1: String,
		mdwLcConfig2: String,
		ordGcConfig1: String,
		ordGcConfig2: String,
		ordGcConfig3: String,
		mdwGcConfig1: String,
		mdwGcConfig2: String,
		mdwGcConfig3: String,
		cdConfig1: String,
		cdConfig2: String,
		ordAfldConfig1: String,
		ordAfldConfig2: String,
		ordAfldConfig3: String,
		mdwAfldConfig1: String,
		mdwAfldConfig2: String,
		mdwAfldConfig3: String,
		ordDeprwyConfig1: String,
		ordDeprwyConfig2: String,
		mdwDeprwyConfig1: String,
		mdwDeprwyConfig2: String,
		mdwArrrwyConfig1: String,
		mdwArrrwyConfig2: String,
		ordArrrwyConfig1: String,
		ordArrrwyConfig2: String,
		ordApptype1: String,
		mdwApptype2: String,
		mdwFlow: String,
		ordFlow: String,
		tmuOnline: Boolean,
		textInput: String,
		pekue: String,
		olinn: String,
		noony: String,
		mykie: String,
		pmpkn: String,
		raynr: String,
		ebake: String,
		dufee: String,
		moble: String,
		lewke: String,
		earnd: String,
		dennt: String,
		cmsky: String,
		bacen: String,
		acito: String,
		pekueStatus: String,
		olinnStatus: String,
		noonyStatus: String,
		mykieStatus: String,
		pmpknStatus: String,
		raynrStatus: String,
		ebakeStatus: String,
		dufeeStatus: String,
		mobleStatus: String,
		lewkeStatus: String,
		earndStatus: String,
		denntStatus: String,
		cmskyStatus: String,
		bacenStatus: String,
		acitoStatus: String,
		departureGroundStop: String,
		cictextInput: String,
		sataptConfig1: String,
		sataptConfig2: String,
		sataptConfig3: String,
		sataptConfig4: String,
		sataptConfig5: String,
		sataptConfig6: String,
	},
	{
		collection: 'config',
	},
);

export default m.model('Config', configSchema);
