import { config } from 'dotenv';
import m from 'mongoose';

const configSchema = new m.Schema({
	id: String,
	lcConfig1: String, 
	lcConfig2: String, 
	lcConfig3: String, 
	lcConfig4: String, 
	gcConfig1: String,
	gcConfig2: String,
	gcConfig3: String,
	gcConfig3: String,
	cdConfig1: String,
	cdConfig2: String,
	afldConfig1: String,
	afldConfig2: String,
	afldConfig3: String,
	afldConfig4: String,
	deprwyConfig1: String,
	deprwyConfig2: String,
	arrrwyConfig1: String,
	arrrwyConfig2: String,
	apptype1: String,
	apptype2: String,
	flow: String,
	tmuOnline: Boolean,
	textInput: String,
	pekue: String,
	olinn: String,
	noony: String,
	mykie: String,
	pmpkn: String,
	raynr: String,
	ebake: String,
	dufee: String,
	moble: String,
	lewke: String,
	earnd: String,
	dennt: String,
	cmsky: String,
	bacen: String,
	acito: String,
	pekueStatus: String,
	olinnStatus: String,
	noonyStatus: String,
	mykieStatus: String,
	pmpknStatus: String,
	raynrStatus: String,
	ebakeStatus: String,
	dufeeStatus: String,
	mobleStatus: String,
	lewkeStatus: String,
	earndStatus: String,
	denntStatus: String,
	cmskyStatus: String,
	bacenStatus: String,
	acitoStatus: String,
	departureGroundStop: String,
	cictextInput: String,

}, {
	collection: "config"
});

export default m.model('Config', configSchema);